name: CI

on:
  pull_request:
    branches:
      - '**'
      - '*'
  push:
    branches:
      - '*'
      - '**'
      - '!renovate/**'
    tags:
      - '.*'

jobs:
  build:
    runs-on: ubuntu-latest

    name: CI

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - run: npm i npm -g

      - uses: actions/cache@v2
        id: cache
        with:
          path: ./node_modules
          key: npm-14-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

#      - run: npm run test:unit
      - run: npm run lint

      - run: npm run build
